# Generated by Django 2.0.5 on 2018-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlt',
            options={'ordering': ['created'], 'verbose_name': '大乐透', 'verbose_name_plural': '大乐透'},
        ),
        migrations.AlterField(
            model_name='dlt',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
