# Generated by Django 2.0.5 on 2018-05-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlt', '0002_auto_20180515_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlt',
            options={'ordering': ['-created'], 'verbose_name': '大乐透', 'verbose_name_plural': '大乐透'},
        ),
    ]
