# Generated by Django 2.0.5 on 2018-05-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlt', '0002_auto_20180521_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-num',)},
        ),
    ]
