# Generated by Django 2.0.5 on 2018-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActDlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('f', models.IntegerField()),
                ('g', models.IntegerField()),
                ('num', models.IntegerField()),
                ('published', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '大乐透开奖',
                'verbose_name_plural': '大乐透开奖',
            },
        ),
        migrations.CreateModel(
            name='DLT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('f', models.IntegerField()),
                ('g', models.IntegerField()),
                ('num', models.IntegerField()),
                ('status', models.CharField(choices=[('1', '一等奖'), ('2', '二等奖'), ('3', '三等奖'), ('4', '四等奖'), ('5', '五等奖'), ('6', '六等奖'), ('un', '待开奖'), ('0', '未中奖')], default='un', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '大乐透',
                'verbose_name_plural': '大乐透',
            },
        ),
    ]
